
Validação e Tratamento de Dados Ausentes: Leia halloween_vendas.csv com usando
pd. da biblioteca Pandas, e armazene os dados em um DataFrame.
Preencha categoria vazia com a string 'isem categoria". Verifique quantidade (inteiro
maior que zero) e preco_unitario (preenchido e não negativo). Marque ou separe
registros com problemas, sem inventar valores. Justifique sua regra nos comentários e
no README. Conte os problemas por campo e o total de pedidos afetados, sem somar
ocorrências que podem se sobrepor.
Padronização de Strings e Regex: Utilize strip() e .lower() na coluna categoria e
aplique obrigatoriamente re.sub() para retirar pontuações indevidas, preservando
letras e espaços significativos. As categorias preenchidas deste CSV usam letras sem
acentos. Se o resultado ficar vazio, use "'sem categoria". Padronize canal_venda para
Mercado, Loja física e Web. Conte categorias vazias preenchidas e categorias não
vazias alteradas separadamente.
Lógica de Regra de Negócio (Filtros e Validação): Com condicionais, investigue se
todos os registros com data_entrega vazia têm status_pedido igual a Cancelado.
Conte separadamente pedidos sem entrega e cancelados e pedidos sem entrega com
outros status. Mostre até três exemplos do segundo grupo. Se houver um
contraexemplo, a hipótese é falsa na base. Não altere 0 status nem invente datas de
entrega.
Formatação Temporal (Datetime): Converta data_venda com datetime.strptime(), do
formato '2025-10-12 143500". Preserve o texto original, extraia ano, mês, dia e hora e
crie uma apresentação brasileira com strftime(), como "12/10/2025". Conte e marque ou
separe datas inválidas ou vazias, permitindo continuar o processamento. Não
substitua pela data de hoje.
Relatório de Status Manual e Exploração: Exiba total de linhas lidas, categorias
preenchidas e padronizadas, problemas numéricos, datas inválidas e total de
cancelados, além dos dois grupos sem data de entrega. Conte pedidos por canal
2
6.
SCTEC
usando registros com canal reconhecido; por ano-mês, use registros com data_venda
válida. Nessas duas contagens, inclua todos os status e informe exclusões. Não agrupe
apenas por mês, pois isso mistura anos. Produza duas descobertas: uma por canal e
outra por período, com números, interpretação e limitação. Essas contagens
representam pedidos registrados, não receita ou vendas concluídas
Relatório e insights: Crie um arquivo chamado
report . md no repositório GitHub de
entrega. Apresente um resumo dos principais achados e insights, apoiados nos
resultados da sua análise, com 1.500 a 3.000 caracteres, incluindo espaços. Utilize uma
ferramenta de IA para conferir a contagem de caracteres do texto final.

In [9]:
%pip install pandas

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.1.0)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.9.0 in .\.venv\Lib\site-packages (from pandas) (3.0.0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.6)
Requirement already satisfied: six>=1.6 in .\.venv\Lib\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import pandas as pd

In [11]:
from pathlib import Path
from datetime import datetime
from decimal import Decimal, InvalidOperation
import re
import pandas as pd
from IPython.display import display, Markdown

Leia halloween_vendas.csv com usando
pd. da biblioteca Pandas, e armazene os dados em um DataFrame

In [12]:
caminho = "halloween_vendas.csv"
df = pd.read_csv(caminho, sep=",", encoding="utf-8", dtype=str)

In [13]:
df

,pedido_id,data_venda,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega
0,844,2025-11-21 18:02:35,Fantasia de vampiro,Fantasia,Loja física,Curitiba,3,132.5,72.08,15,Cancelado,Adulto,G,NaN
1,378,2024-10-29 18:41:26,Fantasia de bruxa,FANTASIA!!!,Loja física,Maringá,3,110,57,5,Concluído,Adulto,M,2024-11-03 18:41:26
2,953,2025-09-05 21:16:09,Fantasia de bruxa,Fantasia,Web,Maringá,2,116.6,60.42,5,Concluído,Adulto,M,2025-09-10 21:16:09
3,11,2024-11-08 11:29:44,Mascara assustadora,Acessorio,Loja física,Cascavel,1,35,12,15,Concluído,Todos,Unico,2024-11-11 11:29:44
4,1335,2025-08-23 11:22:05,Mascara assustadora,Acessorio,Mercado,Curitiba,3,37.1,12.72,0,Concluído,Todos,Unico,2025-08-25 11:22:05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,660,2024-11-09 09:13:34,Mascara assustadora,Acessorio,loja física,Maringá,2,35,12,0,Concluído,Todos,Unico,2024-11-11 09:13:34
1496,772,2025-10-21 15:40:35,Fantasia de bruxa,Fantasia,Loja física,Maringá,1,116.6,60.42,5,Concluído,Adulto,M,2025-10-25 15:40:35
1497,25,2024-09-22 19:03:42,Chapeu de bruxa,Acessorio,Web,Maringá,3,22,8,5,Concluído,Todos,Unico,2024-09-24 19:03:42
1498,1147,2025-10-22 16:00:11,Chapeu de bruxa,Acessorio,Mercado,Cascavel,5,23.32,8.48,0,Concluído,Todos,Unico,2025-10-26 16:00:11
1499,271,2024-09-11 14:55:09,Chapeu de bruxa,Acessorio,Mercado,Londrina,2,22,8,0,Concluído,Todos,Unico,2024-09-14 14:55:09

Preencha categoria vazia com a string "sem categoria"

In [14]:
df['categoria']

0              Fantasia
1         FANTASIA!!!
2              Fantasia
3             Acessorio
4             Acessorio
             ...
1495          Acessorio
1496           Fantasia
1497          Acessorio
1498          Acessorio
1499          Acessorio
Name: categoria, Length: 1500, dtype: str

In [15]:
vazios = df['categoria'].isna() | df['categoria'].str.strip().eq('')

df.loc[vazios]

,pedido_id,data_venda,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega
39,80,2024-09-09 19:01:07,Mascara assustadora,NaN,Web,Maringá,3,35,12,0,Concluído,Todos,Unico,2024-09-11 19:01:07
55,1040,2025-11-04 21:49:35,Fantasia de bruxa,NaN,Web,Maringá,2,116.6,60.42,20,Concluído,Adulto,M,2025-11-06 21:49:35
157,320,2024-08-21 14:30:09,Chapeu de bruxa,NaN,Mercado,Londrina,6,22,8,0,Concluído,Todos,Unico,2024-08-23 14:30:09
233,960,2025-11-01 16:57:10,Fantasia de bruxa,NaN,Loja física,Maringá,1,116.6,60.42,15,Concluído,Adulto,M,2025-11-03 16:57:10
240,720,2024-08-05 21:36:11,Fantasia de fantasma,NaN,Web,Cascavel,2,75,39,0,Concluído,Infantil,M,NaN
371,1120,2025-11-06 14:30:43,Fantasia de fantasma,NaN,Loja física,Londrina,3,79.5,41.34,25,Concluído,Infantil,M,2025-11-08 14:30:43
395,1200,2025-09-23 11:28:37,Fantasia de vampiro,NaN,Loja física,Maringá,2,132.5,72.08,0,Cancelado,Adulto,G,NaN
418,480,2024-10-24 18:22:52,Fantasia de vampiro,NaN,Web,Maringá,1,125,68,0,Concluído,Adulto,G,2024-10-26 18:22:52
500,1360,2025-10-14 10:19:55,Mascara assustadora,NaN,Mercado,Londrina,4,37.1,12.72,0,Concluído,Todos,Unico,2025-10-16 10:19:55
777,800,2025-09-12 20:30:20,Fantasia de fantasma,NaN,Web,Londrina,2,79.5,41.34,0,Concluído,Infantil,M,2025-09-14 20:30:20
816,880,2025-11-14 10:55:57,Fantasia de vampiro,NaN,Loja física,Cascavel,2,132.5,72.08,0,Cancelado,Adulto,G,NaN
1001,400,2024-10-06 13:18:46,Chapeu de bruxa,NaN,Mercado,Londrina,5,22,8,5,Concluído,Todos,Unico,2024-10-08 13:18:46
1059,240,2024-08-03 12:40:11,Chapeu de bruxa,NaN,Loja física,Curitiba,2,22,8,0,Concluído,Todos,Unico,2024-08-05 12:40:11
1167,560,2024-10-18 12:39:53,Chapeu de bruxa,NaN,Loja física,Curitiba,1,22,8,0,Concluído,Todos,Unico,2024-10-20 12:39:53
1282,1280,2025-08-16 15:39:42,Fantasia de vampiro,NaN,Loja física,Maringá,2,132.5,72.08,5,Concluído,Adulto,G,2025-08-18 15:39:42
1307,160,2024-10-01 21:19:10,Fantasia de bruxa,NaN,Web,Londrina,2,110,57,10,Concluído,Adulto,M,2024-10-03 21:19:10
1309,1440,2025-11-16 19:05:21,Fantasia de bruxa,NaN,Web,Cascavel,2,116.6,60.42,15,Cancelado,Adulto,M,NaN
1472,640,2024-10-31 10:44:42,Fantasia de vampiro,NaN,Loja física,Londrina,2,125,68,10,Concluído,Adulto,G,2024-11-02 10:44:42

In [16]:
df.loc[vazios, 'categoria'] = 'sem categoria'

Verifique quantidade (inteiro
maior que zero) e preco_unitario (preenchido e não negativo)

In [17]:
quantidade = pd.to_numeric(df['quantidade'], errors='coerce')
preco = pd.to_numeric(df['preco_unitario'], errors='coerce')

validos = (
    quantidade.notna()
    & (quantidade > 0)
    & (quantidade % 1 == 0)
    & preco.notna()
    & (preco >= 0)
)

print(f"Registros válidos: {validos.sum()}")

Registros válidos: 1481

# dados vazios

In [18]:
# Preenche os valores vazios da coluna categoria com 'Não Informado'
df['categoria'] = df['categoria'].fillna('Não Informado')
display(df.loc[vazios])

,pedido_id,data_venda,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega
39,80,2024-09-09 19:01:07,Mascara assustadora,sem categoria,Web,Maringá,3,35,12,0,Concluído,Todos,Unico,2024-09-11 19:01:07
55,1040,2025-11-04 21:49:35,Fantasia de bruxa,sem categoria,Web,Maringá,2,116.6,60.42,20,Concluído,Adulto,M,2025-11-06 21:49:35
157,320,2024-08-21 14:30:09,Chapeu de bruxa,sem categoria,Mercado,Londrina,6,22,8,0,Concluído,Todos,Unico,2024-08-23 14:30:09
233,960,2025-11-01 16:57:10,Fantasia de bruxa,sem categoria,Loja física,Maringá,1,116.6,60.42,15,Concluído,Adulto,M,2025-11-03 16:57:10
240,720,2024-08-05 21:36:11,Fantasia de fantasma,sem categoria,Web,Cascavel,2,75,39,0,Concluído,Infantil,M,NaN
371,1120,2025-11-06 14:30:43,Fantasia de fantasma,sem categoria,Loja física,Londrina,3,79.5,41.34,25,Concluído,Infantil,M,2025-11-08 14:30:43
395,1200,2025-09-23 11:28:37,Fantasia de vampiro,sem categoria,Loja física,Maringá,2,132.5,72.08,0,Cancelado,Adulto,G,NaN
418,480,2024-10-24 18:22:52,Fantasia de vampiro,sem categoria,Web,Maringá,1,125,68,0,Concluído,Adulto,G,2024-10-26 18:22:52
500,1360,2025-10-14 10:19:55,Mascara assustadora,sem categoria,Mercado,Londrina,4,37.1,12.72,0,Concluído,Todos,Unico,2025-10-16 10:19:55
777,800,2025-09-12 20:30:20,Fantasia de fantasma,sem categoria,Web,Londrina,2,79.5,41.34,0,Concluído,Infantil,M,2025-09-14 20:30:20
816,880,2025-11-14 10:55:57,Fantasia de vampiro,sem categoria,Loja física,Cascavel,2,132.5,72.08,0,Cancelado,Adulto,G,NaN
1001,400,2024-10-06 13:18:46,Chapeu de bruxa,sem categoria,Mercado,Londrina,5,22,8,5,Concluído,Todos,Unico,2024-10-08 13:18:46
1059,240,2024-08-03 12:40:11,Chapeu de bruxa,sem categoria,Loja física,Curitiba,2,22,8,0,Concluído,Todos,Unico,2024-08-05 12:40:11
1167,560,2024-10-18 12:39:53,Chapeu de bruxa,sem categoria,Loja física,Curitiba,1,22,8,0,Concluído,Todos,Unico,2024-10-20 12:39:53
1282,1280,2025-08-16 15:39:42,Fantasia de vampiro,sem categoria,Loja física,Maringá,2,132.5,72.08,5,Concluído,Adulto,G,2025-08-18 15:39:42
1307,160,2024-10-01 21:19:10,Fantasia de bruxa,sem categoria,Web,Londrina,2,110,57,10,Concluído,Adulto,M,2024-10-03 21:19:10
1309,1440,2025-11-16 19:05:21,Fantasia de bruxa,sem categoria,Web,Cascavel,2,116.6,60.42,15,Cancelado,Adulto,M,NaN
1472,640,2024-10-31 10:44:42,Fantasia de vampiro,sem categoria,Loja física,Londrina,2,125,68,10,Concluído,Adulto,G,2024-11-02 10:44:42